#!/bin/bash 

mysql -u root southwind <<END
    DELETE FROM products;
    INSERT INTO products (productCode, name, quantity, price) VALUES
         ('PEC', 'Pencil 2B', 10000, 0.48),
         ('PEC', 'Pencil 2H', 8000, 0.49);
    INSERT INTO products (productCode, name) VALUES ('PEC', 'Pencil HB');

    SELECT * FROM products;


END